version: 2
executorType: docker
containerInfo:
  - image: ubuntu:xenial
    cmd: ["/bin/bash"]

stages:
  build:
    steps:
          - type: shell
            command: mkdir /root/comicsdbclient
          - type: shell
            name: Install apt packages
            command: apt-get update && apt-get -y install git libqt5widgets5 wget unzip default-jdk
          - type: checkout
            path: /root/comicsdbclient
          - type: shell
            name: Download Android SDK tools
            command: wget https://dl.google.com/android/repository/tools_r25.2.3-linux.zip; unzip tools_r25.2.3-linux.zip
          - type: shell
            name: Download Gradle and Android stuff
            command: |
              echo $GOOGLE_SERVICES | base64 --decode > ~/comicsdbclient/app/google-services.json
              wget "https://services.gradle.org/distributions/gradle-3.3-all.zip"; unzip gradle-3.3-all.zip
              ( sleep 5 && while [ 1 ]; do sleep 1; echo y; done ) | tools/android update sdk --no-ui --all --filter tools,platform-tools,android-24,extra-google-m2repository,extra-google-google_play_services,extra-android-support,extra-android-m2repository
              echo y | tools/android update sdk --no-ui --all --filter build-tools-25.0.2
              echo y | tools/android update sdk --no-ui --all --filter sys-img-armeabi-v7a-google_apis-24
          - type: shell
            name: Create emulator
            command:  echo no | tools/android create avd -f -n android-24 -t android-24 --abi google_apis/armeabi-v7a
          - type: shell
            name: Start emulator
            command: SHELL=/bin/bash tools/emulator -no-audio -no-window -avd android-24
          - type: shell
            name: Wait for emulator to start
            command: |
              while [ "`platform-tools/adb shell getprop init.svc.bootanim | tr -d '\r' `" != "1" ] ; do sleep 1; done
              sleep 30
              platform-tools/adb shell input keyevent 82
          - type: shell
            name: Build and test application
            command: if [ -e ./gradlew ]; then ./gradlew test assembleDebug connectedAndroidTest -PdisablePreDex;else gradle test assembleDebug connectedAndroidTest -PdisablePreDex;fi
          - type: artifacts-store
            path: app/build/outputs
            destination: build
          - type: test-results-store
            path: app/build/test-results/
          - type: test-results-store
            path: app/build/outputs/androidTest-results/*